# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a8029d9d3fc9bdd159ea79f7cc9937825b39b023a8c802fc5f8b3d82ca70c01024ee93c8c61da1958e4ca1d7dafafee061b56e0427db1ca401db6c7275ea807

test:
  secret_key_base: 0993123067ccd591b83188d81bfc3e71095493ba8e5d37128d28d23fc06c058f4ff482c673f15247483a3650d111d9c8f2868de47462aa54d4c618f318895ea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
